<DateField>:
    orientation: "horizontal"
    Label:
        text: root.field_name
    MDRaisedButton:
        text: root.name_text if root.name_text else "(tap to set)"
        on_release: root.screen.show_date_picker(root.field_name)

<DescriptionField>:
    orientation: "horizontal"
    MDLabel:
        text: "Description"
    MDTextField:
        hint_text: "Description"



<EditTaskScreen>:
    name: "edit_task_screen"
    task_manager: app.task_manager
    BoxLayout:
        orientation: "vertical"
        MDTopAppBar:
            title: "Edit Task" if root.mode == "edit" else "Create Task"
            pos_hint: {"top": 1}
            on_kv_post: self.action_button.elevation = 0
            left_action_items: [["arrow-left", lambda x: root.on_back()]]
            right_action_items: [["delete-forever", lambda x: root.on_delete()], ["content-save", lambda x: root.on_save()]]

        MDScrollView:
            MDList:
                BoxLayout:
                    id: edit_task_options_container
