<MainScreen>:
    name: "main_screen"
    task_manager: app.task_manager
    BoxLayout:
        orientation: "vertical"

        ActionBar:
            ActionView:
                ActionPrevious:
                    title: "Lalonde"
                    with_previous: False
                ActionButton:
                    text: "Create task"
                    on_release: root.on_create_task()

        TaskList:
            id: task_list
            task_manager: app.task_manager
