<TaskWidget>:
    text: str(root.task_data.description) if root.task_data else ""
    on_release: root.on_edit()

    CheckboxLeftWidget:
        id: is_completed
        active: root.task_data.is_completed if root.task_data else False

<TaskList>:
    orientation: "vertical"
    BoxLayout:
        orientation: "horizontal"
        size_hint_y: None
        height: dp(40)

        Label:
            text: "Tasks"

    MDScrollView:
        MDList:
            id: tasks_container
