"""Android notification backend for alarms.

Android-only by design: `jnius` doesn't exist off-device, so *importing* this
module on desktop raises ModuleNotFoundError. That's intentional -- the platform
check belongs at the call site, not as a guard clause in every function here.

Requires minapi >= 26. NotificationChannel and the two-argument
Notification.Builder constructor were both added in API 26; on 24/25 they don't
exist and these calls throw.
"""

import datetime

from jnius import autoclass, cast

# Bumping the suffix is the ONLY way to change a channel's importance, sound, or
# vibration on a device where it already exists -- Android freezes those at
# creation and silently ignores later changes.
CHANNEL_ID = "lalonde_alarms_v1"
CHANNEL_NAME = "Task alarms"

# Generated by p4a from the `services =` line in buildozer.spec, into
# <package.domain>.<package.name>. Changing either of those moves this class.
SERVICE_CLASS = "io.github.sarcasticdweller.lalonde.ServiceAlarm"

# One fixed request code, because exactly one OS alarm is ever registered at a time.
# Reusing it means scheduling a new alarm implicitly replaces the old one and there's
# no way to leak a registration we can no longer find.
ALARM_REQUEST_CODE = 1

# Android gained the exact-alarm app op in API 31. Below that, exact alarms are
# always permitted and canScheduleExactAlarms() doesn't exist.
EXACT_ALARM_PERMISSION_API = 31

NOTIFICATION_ID = 1001 # must not be 1; causes a collision with p4a's ServiceAlarm.getServiceID()


def _get_context():
    """The Context for whichever process we're in.

    The app and the alarm service are separate OS processes with separate
    entrypoints, and each exposes its own Context: `mActivity` is null in the
    service, `mService` is null in the app.
    """
    PythonActivity = autoclass("org.kivy.android.PythonActivity")
    if PythonActivity.mActivity is not None:
        return PythonActivity.mActivity

    PythonService = autoclass("org.kivy.android.PythonService")
    return PythonService.mService


def _get_notification_manager(context):
    Context = autoclass("android.content.Context")
    return cast(
        "android.app.NotificationManager",
        context.getSystemService(Context.NOTIFICATION_SERVICE)
    )


def _get_alarm_manager(context):
    Context = autoclass("android.content.Context")
    return cast(
        "android.app.AlarmManager",
        context.getSystemService(Context.ALARM_SERVICE)
    )


def get_app_files_dir() -> str:
    # KivyMD-agnostic way to find `settings.json` (see: files.settings)
    return cast("java.io.File", _get_context().getFilesDir()).getAbsolutePath()


def create_notification_channel():
    """Registers the alarm channel. Safe to call repeatedly.

    Android treats re-creating an existing channel as a no-op, so this can run on
    every app start (and every service start) without checking first.

    A notification posted to an unregistered channel is silently dropped, so this
    has to happen before any `post_notification()` call in the same process.
    """
    NotificationChannel = autoclass("android.app.NotificationChannel")
    NotificationManager = autoclass("android.app.NotificationManager")

    context = _get_context()

    # IMPORTANCE_HIGH gets a heads-up popup so a reminder isn't easy to miss, but
    # the channel deliberately keeps the default notification sound on the
    # notification stream -- NOT USAGE_ALARM. Silent on vibrate and subject to Do
    # Not Disturb is the intended behavior: punctuality is the goal, not volume.
    channel = NotificationChannel(
        CHANNEL_ID,
        CHANNEL_NAME,
        NotificationManager.IMPORTANCE_HIGH
    )
    channel.setDescription("Reminders for tasks with an alarm: attribute")
    channel.enableVibration(True)

    _get_notification_manager(context).createNotificationChannel(channel)


def post_notification(
    title: str,
    text: str,
    notification_id: int = NOTIFICATION_ID
):
    """Posts an alarm notification.

    Note this fails *silently* if POST_NOTIFICATIONS hasn't been granted (API 33+):
    no exception, nothing in logcat, just no notification. That's the first thing
    to check whenever this appears to run but nothing shows up.
    """
    NotificationBuilder = autoclass("android.app.Notification$Builder")

    context = _get_context()

    builder = NotificationBuilder(context, CHANNEL_ID)
    builder.setContentTitle(title)
    builder.setContentText(text)
    # A notification with no small icon is discarded. Reuse the app's own icon
    # rather than shipping a second drawable.
    builder.setSmallIcon(context.getApplicationInfo().icon)
    builder.setAutoCancel(True)  # dismiss when tapped

    # TODO: setContentIntent so tapping opens the app on the relevant task.

    _get_notification_manager(context).notify(notification_id, builder.build())


# --- Exact alarms --------------------------------------------------------------


def can_schedule_exact_alarms() -> bool:
    """Whether the OS will currently accept an exact alarm from us.

    Check this before EVERY schedule call, not once at startup. The user can revoke
    "Alarms & reminders" at any time, and when they do the system silently cancels
    every exact alarm already registered -- no callback, no exception, alarms just
    stop happening.
    """
    VERSION = autoclass("android.os.Build$VERSION")
    if VERSION.SDK_INT < EXACT_ALARM_PERMISSION_API:
        return True
    return _get_alarm_manager(_get_context()).canScheduleExactAlarms()


def request_exact_alarm_permission():
    """Sends the user to the system "Alarms & reminders" screen.

    SCHEDULE_EXACT_ALARM is an app op, not a runtime permission: there is no dialog
    and requestPermissions() will not surface one. This settings trip is the only
    route. Like the storage permission, there's no result callback -- re-check
    can_schedule_exact_alarms() on resume.

    Activity-only: it starts an Activity, so it cannot be called from the service.
    """
    Intent = autoclass("android.content.Intent")
    Settings = autoclass("android.provider.Settings")
    Uri = autoclass("android.net.Uri")
    PythonActivity = autoclass("org.kivy.android.PythonActivity")
    current_activity = PythonActivity.mActivity

    intent = Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM)
    intent.setData(Uri.parse(f"package:{current_activity.getPackageName()}"))
    current_activity.startActivity(intent)


def _build_alarm_pending_intent(
    context,
    payload: str, 
    *,
    create: bool = True
):
    """The PendingIntent that fires the alarm service.

    The Intent comes from the generated service's own getDefaultIntent() rather than
    being hand-built: it carries nine extras (androidPrivate, pythonHome, pythonPath,
    serviceEntrypoint, ...) that the service needs in order to bootstrap at all.

    getForegroundService -- not getBroadcast, not getActivity -- because the target is
    a foreground service and the app process may be dead when it fires.
    """
    PendingIntent = autoclass("android.app.PendingIntent")
    ServiceAlarm = autoclass(SERVICE_CLASS)

    intent = ServiceAlarm.getDefaultIntent(context, "", "Lalonde", "Alarm", payload)

    flags = PendingIntent.FLAG_IMMUTABLE
    flags |= PendingIntent.FLAG_UPDATE_CURRENT if create else PendingIntent.FLAG_NO_CREATE

    return PendingIntent.getForegroundService(
        context, ALARM_REQUEST_CODE, intent, flags
    )


def schedule_alarm(when: datetime.datetime, payload: str) -> bool:
    """Registers the single OS alarm, replacing whatever was registered before.

    `when` is naive local wall-clock time, matching how alarm: is stored.
    `payload` is the only thing that reaches the service process -- make it the
    alarm's ISO timestamp so the service can look up which tasks are due.

    Returns False if the exact-alarm permission isn't granted; nothing is scheduled
    in that case and the caller should send the user to settings.
    """
    if not can_schedule_exact_alarms():
        return False

    AlarmManager = autoclass("android.app.AlarmManager")
    context = _get_context()

    # setExactAndAllowWhileIdle, not setExact (won't fire during Doze) and not
    # setAlarmClock (Doze-exempt but claims the system's "next alarm" slot and status
    # bar icon -- too loud for a routine reminder).
    _get_alarm_manager(context).setExactAndAllowWhileIdle(
        AlarmManager.RTC_WAKEUP,
        int(when.timestamp() * 1000),  # epoch millis; naive datetime -> local time
        _build_alarm_pending_intent(context, payload),
    )
    return True


def cancel_alarm():
    """Cancels the registered alarm, if there is one. Safe to call when there isn't."""
    context = _get_context()
    # FLAG_NO_CREATE returns null when no matching PendingIntent exists, which is how
    # we tell "nothing scheduled" from "something to cancel".
    pending = _build_alarm_pending_intent(context, "", create=False)
    if pending is None:
        return
    _get_alarm_manager(context).cancel(pending)
    pending.cancel()
